// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtoNx9ycnBWTcEtLLkzM6i2XOObcItXRA',
    appId: '1:795229310507:web:3bf90c23e6c6b013d1a46e',
    messagingSenderId: '795229310507',
    projectId: 'aidx-medical-app',
    authDomain: 'aidx-medical-app.firebaseapp.com',
    storageBucket: 'aidx-medical-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYIN2pbo7P2FcVmuCIf2WUEg9iApklQAA',
    appId: '1:795229310507:android:1462d55923f0e2ebd1a46e',
    messagingSenderId: '795229310507',
    projectId: 'aidx-medical-app',
    storageBucket: 'aidx-medical-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4thWgDjv9RjHpKdxlVoYNFSVLTLudn2s',
    appId: '1:795229310507:ios:da638db5253451bcd1a46e',
    messagingSenderId: '795229310507',
    projectId: 'aidx-medical-app',
    storageBucket: 'aidx-medical-app.firebasestorage.app',
    iosBundleId: 'com.medigay.app.medigayApp',
  );
}
